services:
  - type: web
    name: cloude-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: VIP_CHAT_ID
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: DB_PATH
        value: /data/cloude.db
    disk:
      name: db-disk
      mountPath: /data
      sizeGB: 1
